### ISSUE TITLE
VITO server error during compute_result()

### ISSUE THREAD

**Issue by fdetsch** [Open-EO/openeo-r-client#58]
I get 

```r
SERVER-ERROR: An error occurred while calling o3247140.datacube_seq.
: java.lang.NullPointerException
	at org.openeo.geotrellissentinelhub.PyramidFactory.datacube_seq(PyramidFactory.scala:100)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)
```

upon running [VITO-examples.Rmd](https://github.com/Open-EO/openeo-r-client/blob/master/examples/VITO-examples.Rmd). The error occurs at `compute_result()`. 

This used to work just fine only last week. Other backends (tested with GEE) don't seem to be affected. Any ideas?

**Comment by flahn** [comment]
This seems to be a server error, which is returned from VITO back-end. Maybe @jdries has some more insights or you may raise here: https://github.com/Open-EO/openeo-geotrellis-extensions

**Comment by flahn** [comment]
Or maybe there has been an update rollout, just to be sure, you might check again tomorrow or in the next days.

**Comment by fdetsch** [comment]
I'll keep an eye on it. Problem is still persistent.

**Comment by fdetsch** [comment]
Backend is back online.

**Comment by fdetsch** [comment]
With the latest R build, I now see

```r
SERVER-ERROR: An error occurred while calling None.org.openeo.geotrellissentinelhub.PyramidFactory. Trace:
py4j.Py4JException: Constructor org.openeo.geotrellissentinelhub.PyramidFactory([class java.lang.String, class java.lang.String, class java.lang.String, class org.openeo.geotrellissentinelhub.SampleType$Val]) does not exist
	at py4j.reflection.ReflectionEngine.getConstructor(ReflectionEngine.java:179)
	at py4j.reflection.ReflectionEngine.getConstructor(ReflectionEngine.java:196)
	at py4j.Gateway.invoke(Gateway.java:237)
	at py4j.commands.ConstructorCommand.invokeConstructor(ConstructorCommand.java:80)
	at py4j.commands.ConstructorCommand.execute(ConstructorCommand.java:69)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)
```

which is somewhat different from the output I last received when VITO was down. The trace remains the same for Python, only with different header:

```python
OpenEoApiError: [500] unknown: An error occurred while calling None.org.openeo.geotrellissentinelhub.PyramidFactory. Trace:
...
```

Could this be related to this issue or is something else going on? Strange thing, my `compute_result()` call managed to download the requested file once, but then failed again the next time I ran the exact same code. 

I was browsing through the openEO repositories, but couldn't find any related explicitly to the VITO backend. Maybe you can provide guidance here as well.
